[package]
name = "tanf-tools"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tanf-fill"
path = "src/fill.rs"

[dependencies]
rztamp = { path = "../rztamp" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
